# Generate documentation with:
#   generate-schema-doc config_schema.yml doc/config_schema.md
# TODO: add descriptions for everything
required:
- scenario_id
- model
- agents
- fleet
- options
- competition
properties:
  scenario_id: 
    type: string
    description: scenario identifier
  model: 
    type: object
    required:
    - duration
    - nb_iterations
    - reporting
    properties:
      duration:
        description: time a simulation runs for
        type: number
      nb_iterations:
        description: number of iterations per simulation every scenario is tested for
        type: number
      reporting:
        description: indicates if a scenario run reports using all print statements in the script (False --> only report what scenario the model starts running and the total runtime)
        type: bool
  agents: 
    description: Settings for the agents in the model; see agent_schema.yml
    type: array
  fleet:
    type: object
    required:
    - receiver_choice
    properties:
      receiver_choice:
        type: object
        required:
        - group_attributes
        properties:
          group_attributes:
            type: object
            required:
            - nb_groups
            - group_formation
            - group_dynamics
  options: 
    type: object
    required:
    - nb_options
    - growth
    - stock_reset
    properties:
      growth:
        type: object
        required:
        - growth_type
        - growth_attributes
        properties:
          growth_attributes:
            type: object
            required:
            - growth_factor
      stock_reset:
        type: object
        required:
        - name
        - reset_probability
        - uniform_attributes
        - normal_attributes
        properties:
          uniform_attributes:
            type: object
            required:
            - min_stock
            - max_stock
          normal_attributes:
            type: object
            required:
            - init_stock
            - sd_init_stock
  competition: 
    type: object
    required:
    - name
    - interference_attributes
    properties:
      interference_attributes:
        type: object
        required:
        - interference_factor